
- !ruby/object:Rubber::Configuration::InstanceItem 
  domain: dojitsu.com
  external_host: ec2-50-16-148-218.compute-1.amazonaws.com
  external_ip: 107.21.205.253
  image_id: ami-fd589594
  image_type: m1.large
  instance_id: i-77c44b12
  internal_host: ip-10-118-6-52.ec2.internal
  internal_ip: 10.118.6.52
  name: bleeding
  platform: linux
  roles: 
  - !ruby/object:Rubber::Configuration::RoleItem 
    name: web
    options: {}

  - !ruby/object:Rubber::Configuration::RoleItem 
    name: haproxy
    options: {}

  - !ruby/object:Rubber::Configuration::RoleItem 
    name: app
    options: {}

  - !ruby/object:Rubber::Configuration::RoleItem 
    name: passenger
    options: {}

  - !ruby/object:Rubber::Configuration::RoleItem 
    name: apache
    options: {}

  - !ruby/object:Rubber::Configuration::RoleItem 
    name: db
    options: 
      primary: true
  - !ruby/object:Rubber::Configuration::RoleItem 
    name: mysql_master
    options: {}

  - !ruby/object:Rubber::Configuration::RoleItem 
    name: mongodb
    options: {}

  root_device_type: ebs
  security_groups: 
  - dojitsu_production_default
  - dojitsu_production_web
  - dojitsu_production_bleeding
  - dojitsu_production_haproxy
  - dojitsu_production_app
  - dojitsu_production_passenger
  - dojitsu_production_apache
  - dojitsu_production_db
  - dojitsu_production_mysql_master
  - dojitsu_production_mongodb
  static_ip: 107.21.205.253
  zone: us-east-1a
- volumes: {}

  static_ips: 
    dev: 50.19.123.249
    bleeding: 107.21.205.253
